name: Quick repository checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-checks:
    name: Run quick checks script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run quick checks
        # capture output and return code so we can comment on PRs
        run: |
          set -o pipefail
          python scripts/quick_checks.py 2>&1 | tee quick_checks.out
          echo $? > quick_checks.rc

      - name: Read quick checks output
        id: read_output
        run: |
          # Safely set the content of quick_checks.out to an output variable
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat quick_checks.out || true
          echo "EOF" >> $GITHUB_OUTPUT
          rc=$(cat quick_checks.rc || echo "")
          echo "rc=$rc" >> $GITHUB_OUTPUT

      - name: Post or update single PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Quick checks status:**
            
            Exit code: `${{ steps.read_output.outputs.rc }}`
            
            <details>
            <summary>Output</summary>

            ${{ steps.read_output.outputs.body }}

            </details>
          identifier: quick-checks-report

      - name: Fail job if checks failed
        run: |
          rc=$(cat quick_checks.rc)
          if [ "$rc" != "0" ]; then
            echo "Quick checks failed (exit code $rc) -- see PR comment for details"
            exit $rc
          fi
